# Generated by Django 3.0.3 on 2020-12-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('size', models.DecimalField(decimal_places=3, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('lei', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=128)),
            ],
        ),
    ]
