# Generated by Django 3.0.3 on 2020-12-14 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0003_bond_maturity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
