# Generated by Django 3.0.3 on 2020-12-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_bond_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='user',
            new_name='users',
        ),
    ]
