# Generated by Django 3.0.3 on 2020-12-14 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0005_auto_20201214_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='users',
        ),
        migrations.AddField(
            model_name='bond',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
